from pygenic import *

class Core(object):
	backends = None

	def __init__(self):
		signature = 'generated(pc : uint, inst : uint, branched : ref[bool]) -> bool'
		with Module() as self.module:
			Comment('Autogenerated by emugen. DO NOT EDIT')
			with Function(signature) as func:
				self.decoder(func)
